language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

notifications:
  email: false

before_script:
  - npm prune

before_deploy:
  - 'git fetch --tags;
     if [ ! $(git tag -l v* | tail -n1) ]; then
       git tag v0.0.0;
     fi;'

deploy:
  provider: script
  script: npm run semantic:release
  skip_cleanup: true
  on:
    branch: master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/