language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

notifications:
  email: false

before_script:
  - npm prune

after_success:
  - echo "testing... ${REPO}"
  - echo "testing... ${TRAVIS_REPO_SLUG}"
  - npm run semantic:release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/