language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

notifications:
  email: false

before_script:
  - npm prune

after_success:
  - 'git config --local user.name "Travis CI";
     git config --local user.email "builds@travis-ci.org";
     git fetch --tags;
     if [ ! $(git tag -l v* | tail -n1) ]; then
       git tag v0.0.0;
     fi;'
  - npm run semantic:release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/