language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm prune
after_success:
  - 'git fetch --tags;
     if [[ $(git tag) ]]; then
       echo "tags exist";
     else
       git tag v0.0.0;
       git push --tags;
     fi;'
  - npm run semantic:release

